<?php

use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        }
        \Illuminate\Support\Facades\DB::table('bookings')->truncate();
        \Illuminate\Support\Facades\DB::table('bookings')->insert([
            [
                'id' => 1,
                'total_price' => 12120000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trangtran@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 2,
                'total_price' => 18180000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],[
                'id' => 3,
                'total_price' => 12120000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 4,
                'total_price' => 32775000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
            ],[
                'id' => 5,
                'total_price' => 19665000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-19)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-19)->format('Y-m-d H:i:s'),
            ],[
                'id' => 6,
                'total_price' => 7072500,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 7,
                'total_price' => 14145000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 8,
                'total_price' => 16170000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(2)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(2)->format('Y-m-d H:i:s'),
            ],[
                'id' => 9,
                'total_price' => 8085000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 10,
                'total_price' => 32472832,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 11,
                'total_price' => 8106958,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
            ],[
                'id' => 12,
                'total_price' => 40440000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 13,
                'total_price' => 11144589,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
            ],[
                'id' => 14,
                'total_price' => 64279140,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-16)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-16)->format('Y-m-d H:i:s'),
            ],[
                'id' => 15,
                'total_price' => 38505000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 16,
                'total_price' => 484302000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
            ],[
                'id' => 17,
                'total_price' => 69186000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 18,
                'total_price' => 33181270,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 19,
                'total_price' => 5850395,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 20,
                'total_price' => 11864934,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-11)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-11)->format('Y-m-d H:i:s'),
            ],[
                'id' => 21,
                'total_price' => 3036375,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
            ],[
                'id' => 22,
                'total_price' => 692539,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 23,
                'total_price' => 4577920,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(7)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(7)->format('Y-m-d H:i:s'),
            ],[
                'id' => 24,
                'total_price' => 10909090,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 25,
                'total_price' => 11465440,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 26,
                'total_price' => 1186665,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 27,
                'total_price' => 2474026,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
            ],[
                'id' => 28,
                'total_price' => 5665830,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 29,
                'total_price' => 5665830,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 30,
                'total_price' => 8029795,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
            ],[
                'id' => 31,
                'total_price' => 1838175,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
            ],[
                'id' => 32,
                'total_price' => 9190875,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
            ],[
                'id' => 33,
                'total_price' => 14824000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 34,
                'total_price' => 3918920,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 35,
                'total_price' => 10130795,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],[
                'id' => 36,
                'total_price' => 6078477,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],[
                'id' => 37,
                'total_price' => 19439640,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 38,
                'total_price' => 4319920,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 39,
                'total_price' => 24034632,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(6)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(6)->format('Y-m-d H:i:s'),
            ],[
                'id' => 40,
                'total_price' => 11144589,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 41,
                'total_price' => 42107865,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 42,
                'total_price' => 30791800,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 43,
                'total_price' => 6636254,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 44,
                'total_price' => 29251975,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-13)->format('Y-m-d H:i:s'),
            ],[
                'id' => 45,
                'total_price' => 48069264,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 46,
                'total_price' => 5213060,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 47,
                'total_price' => 5234636,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 48,
                'total_price' => 12743080,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 49,
                'total_price' => 31989560,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
            ],[
                'id' => 50,
                'total_price' => 7606400,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 51,
                'total_price' => 3803200,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
            ],[
                'id' => 52,
                'total_price' => 2833600,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(2)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(2)->format('Y-m-d H:i:s'),
            ],[
                'id' => 53,
                'total_price' => 4065600,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 54,
                'total_price' => 4449774,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 55,
                'total_price' => 8109357,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 56,
                'total_price' => 10110000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],[
                'id' => 57,
                'total_price' => 5667200,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
            ],[
                'id' => 58,
                'total_price' => 2964800,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 59,
                'total_price' => 3156887,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],[
                'id' => 60,
                'total_price' => 7068554,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-12)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-12)->format('Y-m-d H:i:s'),
            ],[
                'id' => 61,
                'total_price' => 607275,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-14)->format('Y-m-d H:i:s'),
            ],[
                'id' => 62,
                'total_price' => 3462695,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-15)->format('Y-m-d H:i:s'),
            ],[
                'id' => 63,
                'total_price' => 1831168,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(9)->format('Y-m-d H:i:s'),
            ],[
                'id' => 64,
                'total_price' => 1090909,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(6)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(6)->format('Y-m-d H:i:s'),
            ],[
                'id' => 65,
                'total_price' => 2293088,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(4)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(4)->format('Y-m-d H:i:s'),
            ],[
                'id' => 66,
                'total_price' => 2373330,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 3,
                'first_name' => 'Ha',
                'last_name' => 'Thanh',
                'email' => 'hathanh@gmaill.com',
                'created_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 67,
                'total_price' => 1237013,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 5,
                'first_name' => 'Hai',
                'last_name' => 'Tuan',
                'email' => 'haituan@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],[
                'id' => 68,
                'total_price' => 8085000,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 4,
                'first_name' => 'Cong',
                'last_name' => 'Manh',
                'email' => 'congmanh@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
            ],[
                'id' => 69,
                'total_price' => 3156887,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 1,
                'first_name' => 'Tran',
                'last_name' => 'Trang',
                'email' => 'trantrang@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],[
                'id' => 70,
                'total_price' => 7697950,
                'payment_type' => 'paypal',
                'status' => 1,
                'account_id' => 2,
                'first_name' => 'Hoang',
                'last_name' => 'Huy',
                'email' => 'hoanghuy@gmail.com',
                'created_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ]
        ]);

        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        }
    }
}
